version: '2'

services:
  php:
    build: ./
    volumes:
      - ./:/run/php/
    links:
      - mysql:db
    env_file:
      - env/pushover        
        
  mysql:
    image: hypriot/rpi-mysql        
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: my_casa
