version: '2'

services:
  php:
    build: ./
    volumes:
      - ./:/usr/share/burgeramt-termin
    links:
      - mysql:db
    command: tail -f /dev/null        
        
  mysql:
    image: hypriot/rpi-mysql        
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: my_casa
